### ISSUE TITLE
使用求助

### ISSUE THREAD

**Issue by saowu** [alexwjj/vue-iframe-print#20]
你好，请问你这个demo的printObj怎么打印的啊，也没看见printObj，只看到了printDiv2
![image](https://github.com/alexwjj/vue-iframe-print/assets/33569619/426d91a0-8a4e-4963-babe-0207f527b431)
![image](https://github.com/alexwjj/vue-iframe-print/assets/33569619/0dd4a329-b8d7-4e4f-b4cb-ff866fd49252)

**Comment by LiuwqGit** [comment]
printObj 是一个对象，在data中定义的。
此对象可以包含的内容更多，比如包含了id：printDiv2

**Comment by catPaw-s** [comment]
案例直接报错了，指令绑定对象的时候
